package com.promineotech.ball.entity;

public enum BallType {
	ADIDAS_FINALE_MADRID, ADIDAS_FINALE_19, ADIDAS_FINALE_ISTANBUL, 
	  ADIDAS_FINALE_20, ADIDAS_FINALE_21, ADIDAS_FINALE_PETERSBURG, ADIDAS_FINALE_PEACE, ADIDAS_FINALE_22, JABULANI,
	  JOBULANI, BRAZUCA, BRAZUCA_FINAL_RIO, TELSTAR_18, TELSTAR_18_MECHTA, AL_RIHLA, AL_HILM
}
